[package]
name = "bevy-android-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16", default-features = false, features = ["bevy_core_pipeline", "bevy_render", "bevy_pbr"] }